#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2018-2019 Persistent Systems, Inc.
#

version: '3.2'

services:
    camunda:
        image: igia/igia-camunda
        volumes:
            - ./camunda-config/web.xml:/camunda/webapps/engine-rest/WEB-INF/web.xml
            - ./camunda-config/keycloak.json:/camunda/webapps/engine-rest/WEB-INF/keycloak.json
        environment:
            - DB_DRIVER=org.postgresql.Driver
            - DB_URL=jdbc:postgresql://camunda-postgresql:5432/camunda
            - DB_USERNAME=camunda
            - DB_PASSWORD=
            - WAIT_FOR=camunda-postgresql:5432
            - WAIT_FOR_TIMEOUT=60
        ports:
            - "${CAMUNDA_PORT:-9085}:8080"
        depends_on:
            - keycloak
            - camunda-postgresql

