#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2018-2019 Persistent Systems, Inc.
#

version: '3.2'

services:
  i2b2-python-delete-data:
    image: i2b2/i2b2-python-delete-data:0.1
    stdin_open: true
    tty: true
    command: "python delete_all_data.py"
    environment:
      - I2B2_DB_HOST=i2b2-pg 
    networks:
      - i2b2net
    depends_on:
      - i2b2-pg

networks: 
    i2b2net:
       driver: bridge
