#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2018-2019 Persistent Systems, Inc.
#

version: '3.2'

services:
  i2b2-cdi-sftp:
    image: atmoz/sftp
    command: ${SFTP_USER:-i2b2sftpuser}:${SFTP_PASS:-i2b2sftppass}:1001::concept,data
    #volumes:
    #   - "./sftpdata/concept:/home/${SFTP_USER:-i2b2sftpuser}/concept"
    #   - "./sftpdata/data:/home/${SFTP_USER:-i2b2sftpuser}/data"
    ports:
      - "${I2B2_CDI_SFTP_PORT:-2222}:22"
    networks:
      - i2b2net

networks: 
    i2b2net:
       driver: bridge
      
