#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2018-2019 Persistent Systems, Inc.
#

---
dependency:
  name: galaxy
  options:
    ignore-certs: True

driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos
    box: centos/7  # ubuntu/xenial64
    memory: 4096
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 7000, host: 7000"
      - "vm.network 'forwarded_port', guest: 8091, host: 8091"
      - "vm.network 'forwarded_port', guest: 8761, host: 8761"
      - "vm.network 'forwarded_port', guest: 8888, host: 8888"
      - "vm.network 'forwarded_port', guest: 9080, host: 9080"
#    provider_override_args:
#      - "vm.provision 'shell', inline: 'curl https://bootstrap.pypa.io/get-pip.py  | python --user' "
provisioner:
  name: ansible
  log: True
  env:
    MOLECULE_SSHKEY_PATH: ~/.ssh/id_rsa
    MOLECULE_M2SETTING_PATH: ~/.m2/settings.xml
    STACK_FILE: workflow.yml
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: workflow
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  directory: tests/
  lint:
    name: flake8
