#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2018-2019 Persistent Systems, Inc.
#

---
# Check if correct version of Docker engine is installed and running
- name: detect docker version
  command: docker version --format {% raw %}'{{ .Server.Version }}' {% endraw %}
  register: docker_version
  ignore_errors: True
  changed_when: False

- name: warn if Docker engine pre-req fails
  fail: msg="Please make sure Docker engine v{{ docker_version_min }} or higher is installed and running"
  when: docker_version.stdout is not defined or docker_version.stdout is not version(docker_version_min, '>=')
