#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2018-2019 Persistent Systems, Inc.
#

---
# Check if Git client is installed
- name: detect git client
  command: git --version  # noqa 303
  register: git_version
  ignore_errors: True
  changed_when: False

- name: warn if git client pre-req fails
  fail: msg="Please make sure git client {{ git_version_min }} or higher is installed"
  when: git_version.stdout is not defined or git_version.stdout.split(" ")[2] is not version(git_version_min, '>=')
