#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2018-2019 Persistent Systems, Inc.
#

---
## HIPLATFORM-875: Portainer fails if the admin password is not set within 5 minutes after it starts.
## To resolve this, salted password is passed to --admin-password flag in portainer's docker-compose.
## User can specifcy their desired password by setting env. variable PORTAINER_ADMIN_PASSWORD. If this
## variable is not set, the playbook will generate a random password.
## Please note that the password is set only when portainer container is created for the first time.
## If the password was set earlier, then you will need to remove container as well as volume to reset
## the password.
- name: get portainer admin-password
  set_fact:
    portainer_pass: "{{ lookup('env','PORTAINER_ADMIN_PASSWORD') if lookup('env','PORTAINER_ADMIN_PASSWORD')|length > 0 else  lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}"  # noqa 204
  tags: deploy

- name: hash portainer admin-password   # noqa 301 305
  shell: docker run --rm httpd:2.4-alpine htpasswd -nbB admin '{{ portainer_pass }}'
  register: portainer_pass_hashed
  tags: deploy

- name: get portainer admin-password
  set_fact:
    portainer_pass_salted: "{{ portainer_pass_hashed.stdout.split(':')[1] }}"
  tags: deploy

- name: Remove old portainer, if exists
  docker_container:
    name: local-dev_portainer_1
    state: absent
    force_kill: yes
    keep_volumes: false

- debug:
    msg: "Portainer password : {{ portainer_pass }}"
  tags: deploy
